### ISSUE TITLE
askUser conflic with namedButtons plugin

### ISSUE THREAD

**Issue by mehranrasulian** [mullwar/telebot#109]
Let say we have the bellow code, where we use `askUser` plugin with the `namedButtons`. when I start the bot and click on the `Start Questions` which is a *Named Button*, it asks the `What is your name?` but also asks the second question as the `ROBOT [4]` indicates it, which as you know it is not expected.

```js
const bot = new TeleBot({
	token: 'TOKEN',
	usePlugins: ['askUser', 'namedButtons'],
	pluginConfig: {
		namedButtons: {
			buttons: {
				start: {
					label: 'Start Questions',
					command: '/start_quenstions'
				}
			}
		}
	}
});

bot.on('/start', msg => {

	const markup = bot.keyboard([ ['Start Questions'] ], { resize: true })

	return bot.sendMessage(
		msg.from.id,
		"Would you like to start the questions?",
		{ markup }
	)
})

bot.on('/start_quenstions', msg => {

	return bot.sendMessage(msg.from.id, 'What is your name?', { ask: 'name' })
})

bot.on('ask.name', msg => {

	const name = msg.text
	return bot.sendMessage(
		msg.from.id,
		`Your name is ${name}, what about your last name?`,
		{ ask: 'last'}
	)
})

bot.on('ask.last', msg => {

	const name = msg.text
	return bot.sendMessage(
		msg.from.id,
		`Your last name is ${name}`
	)
})

bot.start()
```

**Let's start the bot**

Mehran Rasulian [1], 
/start

ROBOT [1], 
Would you like to start the questions?

Mehran Rasulian [2], 
Start Questions

**`The bellow two robot messages received at the same time!!`**
ROBOT [3], 
What is your name?

ROBOT [4],
Your name is Start Questions, what about your last name?

Mehran Rasulian [3],
Rasuli

ROBOT [5], 
Your last name is Rasuli

**But when we will not use the `namedButton`** and just use a simple command, the above scenario will not happen and everything is correct.

Already continue using the command event instead of using namedButtons on the production, but please give us a quick fix for this. I tried to find a way to fix this issue but no way yet :disappointed:

**Comment by mullwar** [comment]
Hot fix for askUser plugin:

```js
/*
    Get direct answers from user.
*/

const userList = {};

module.exports = {

    id: 'askUser',

    plugin(bot) {

        // On every text message
        bot.on('text', (msg, props) => {

            const id = msg.chat.id;
            const ask = userList[id];

            // If no question, then it's a regular message
            if (!ask) return;

            // Delete user from list and send custom event
            delete userList[id];
            bot.event('ask.' + ask, msg, props);

        });

        // Before call sendMessage method
        bot.on('sendMessage', (args) => {

            const id = args[0];
            const opt = args[2] || {};

            const ask = opt.ask;

            // If "ask" in options, add user to list
            if (ask) userList[id] = ask;

        });

    }
};
```

**Comment by mehranrasulian** [comment]
Didn't thought it could be easier than  this to change a paramerter 😃.
But I bet it's been hard to find the bug, Good Job @mullwar 🙌.

**Comment by Shemesh** [comment]
this fix does not exist in latest version. can you please publish it.
