### ISSUE TITLE
Does not work ReplyKeyboardRemove

### ISSUE THREAD

**Issue by Fomchenkov** [mullwar/telebot#117]
I want remove reply keyboard.
My code:
```javascript
const replyMarkup = bot.keyboard([], {remove: true})
return bot.sendMessage(msg.chat.id, 'text', {replyMarkup})
```
But this code does nothing.
How I can delete reply keyboard markup?

**Comment by YouTwitFaceTG** [comment]
```return bot.sendMessage(msg.chat.id, 'text', {replyMarkup: 'hide'});```

**Comment by Fomchenkov** [comment]
Thank you. It's work's!

**Comment by YouTwitFaceTG** [comment]
Almost  months later...
