### ISSUE TITLE
How to send messages one by one ?

### ISSUE THREAD

**Issue by eko24ive** [mullwar/telebot#134]
Imagine a have array of strings which I'd like to send to user saving it's order (consequently):
```js
const messages = ['one','two','three','four','five'];
```

What I tried to do is:
```js
messages.map(message => msg.reply.text(message));
```

But messages could be sent in random order, like this:
```
two
one
five
three
four
```

How can I achieve it?

**Comment by LuisTessaro** [comment]
Try using setImmediate() to chain your messages.
Like :
`setImmediate(() => Promise.delay(1000)
        .then(() => bot.sendMessage(msg.from.id, messages[0]))
        .then(() => bot.sendMessage(msg.from.id, messages[1]))
        .then(() => bot.sendMessage(msg.from.id, messages[2]))
        .then(() => bot.sendMessage(msg.from.id, messages[3]))
        .then(() => bot.sendMessage(msg.from.id, messages[5])));`

**Comment by eko24ive** [comment]
it looks like `.then` works fine
