### ISSUE TITLE
Message to every user

### ISSUE THREAD

**Issue by DoodlePain** [mullwar/telebot#138]
Hello, every 30 min my bot is fetching data from a site and comparing with an older version of the same data sends the "news" feed to the users, one by one using the chat id. Is there any method to send messages globally without knowing the chat id? 
Thanks in advance

**Comment by mullwar** [comment]
No, you need to store user/chat ids to do that.

**Comment by DoodlePain** [comment]
Thank you for your answer, there is any smart way to do this? Or should I just store them when they do /start?

**Comment by mullwar** [comment]
@DoodlePain yep, on /start. Also, you can implement /stop to remove user from db.
