### ISSUE TITLE
bug? title ignored in Audio Messages

### ISSUE THREAD

**Issue by sersasa** [mullwar/telebot#14]
This is the example where I am trying to "change"/write the title of the audio file:

bot.on(['/material'], (msg) => {
    var maxNumberElements = 20;
    var index = randomIntInc(0,maxNumberElements);
    var groupID = '113,129';
    var endpoint = 'http://mydomain.com/api/podcast/bygroup?active=true&group=' + 
        groupID + '&limit=' + maxNumberElements + '&radio=' + radioID + '&sort=startDate%20DESC';
    var urlPodcast = '';
    var titlePodcast = '';

```
request
    .get(endpoint)
    .set('Accept', 'application/json')
    .set('Authorization', 'Bearer ' + token4API)
    .end(function(error, response) {
        if (error) {
            console.log('MaratonRadioBot error: ' + error);
        }
        urlPodcast = webAddrRoot4mp3 + response.body[index].mp3Url;
        titlePodcast = response.body[index].title;
        console.log('Titulo del ultimo podcast: ' + titlePodcast);
        console.log('URL del ultimo podcast: ' + urlPodcast);
        bot.sendMessage(msg.from.id, "Descargando el podcast: " + titlePodcast + "...");
        return bot.sendAudio(msg.from.id, urlPodcast, {title: titlePodcast});
});
```

});

In the console I can see the title and the url of the mp3, but when this code is executed, the title is always took from the metadata of the mp3, not from my variable "titlePodcast".
Could you give me some insight?
Thanks in advaced!

**Comment by kosmodrey** [comment]
Hello,

This audio property (and others) is not implemented, it's a bug. Thank you for report.

You can fix this right now, by creating a property modifier:

```js
bot.mod('property', data => {
  // Get audio properties
  const { title, performer } = data.options;
  // Set form data
  if (title) data.form.title = title;
  if (performer) data.form.performer = performer;
  // Return modified data
  return data;
});
```

Now audio properties will work:

```js
// On every text message
bot.on('text', msg => {
  const id = msg.from.id;
  return bot.sendAudio(id, './audio.mp3', {
    title: 'Trololo',
    performer: 'Eduard Hill'
  });
});
```

If you have more questions, please feel free to ask.

**Comment by sersasa** [comment]
Great!! It works perfectly!!
Thanks!
