### ISSUE TITLE
Deployment to Heroku failed

### ISSUE THREAD

**Issue by Hylance** [mullwar/telebot#141]
Hi there, I'm deploying my telegram bot to Heroku but it failed with the following errors: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch.
Looks like the port is not configured correctly. It was running fine on my local though. Any help guys?

**Comment by eko24ive** [comment]
you need to run `worker` on heroku, not `web`
by the way - why did you close issue?
