### ISSUE TITLE
Does this work nicely with multiple Telegram bots on the same server?

### ISSUE THREAD

**Issue by elie222** [mullwar/telebot#152]
Does this work nicely with multiple Telegram bots on the same server?

What is needed to make this work? A new instance for each bot with a different port used each time? Is it possible to have many bots on a single port, or to use something like express to handle passing the messages to the correct bot?

**Comment by lucnat** [comment]
Yes it works perfectly. Just make a `new TeleBot("token")` for each bot, i.e. each token. I have 3 of them running on one server. No need for different ports or so.

**Comment by tennox** [comment]
@elie222 || @mullwar 
/close
