### ISSUE TITLE
This project is abandoned?

### ISSUE THREAD

**Issue by rvalitov** [mullwar/telebot#169]
![image](https://user-images.githubusercontent.com/16267156/68072453-00fd4c80-fd97-11e9-8514-ac53f0f0fa9c.png)

According to the graph there has been no updates over a year. No responses to pull requests and issues at all... 

So, this project is abandoned?

**Comment by mullwar** [comment]
Hi 👋 TeleBot will continue to receive updates. Stay tuned!
