### ISSUE TITLE
message_thread_id in sendmessenger

### ISSUE THREAD

**Issue by phamhuyvn** [mullwar/telebot#233]
I can't send messenger to some topic in supoergroup by add message_thread_id.  Anyone have solution for this

**Comment by VDS13** [comment]
The last update of the library was almost 2 years ago. Therefore, this package does not support topics. Alternatively, you can switch to [node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api), the syntax is similar to telebot and is constantly updated.

**Comment by phamhuyvn** [comment]
after I reply to topic ID, everything is ok
