### ISSUE TITLE
is markup only avaliable for one event only?

### ISSUE THREAD

**Issue by frengkys** [mullwar/telebot#29]
i wonder is it true that telebot just accept one markup on one event only?
this is work for first markup but dont with other markup on else statement....

for example
bot.on('text', msg =>{
   if (msg.text=="yes")
       {  let markup = bot.keyboard([
          ['test yoyow']
       ], { resize: true})
         return bot.sendMessage(
            msg.from.id, 'yoyow' ,{ask : 'day', markup, parse: 'html'}
       }
   else
      {
          let markup = bot.keyboard([
           ['test yayai']
         ], { resize: true})
         return bot.sendMessage(
            msg.from.id, 'yayai' ,{ask : 'day', markup, parse: 'html'}
       }
      }
})

**Comment by kosmodrey** [comment]
Yes, you can pass only one markup object in event.

Your code should work, as this example:

```js

bot.on('text', msg => {
  const id = msg.from.id;
  const message = msg.text;

  if (message == 'hello') {
    
    let markup = bot.keyboard([
      ['hello button']
    ], { resize: true });

    return bot.sendMessage(id, 'Hello :)', { markup });

  } else {

    let markup = bot.keyboard([
      ['bye button']
    ], { resize: true });

    return bot.sendMessage(id, 'Bye :(', { markup });
  
  }
});
```
