### ISSUE TITLE
Is it possible to have http proxy support ?

### ISSUE THREAD

**Issue by thamak** [mullwar/telebot#43]
Hello,

First of all, I really appreciate your work.
Is it possible to add proxy support ?

exemple :
```
const bot: TeleBot = new TeleBot( {
    token: botToken,
    http_proxy: {
        host: "[MyProxy]",
        port: 8080,
        username: "[MyUsername]",
        password: "[MyPwd]"
    },
    polling: {
        ...
    }
});
```

Thank you !

**Comment by kosmodrey** [comment]
Telebot is using [request](https://github.com/request/request) node library, there is an http proxy property. So yes, we can do that :)

**Comment by thamak** [comment]
Perfect ! thanks
