### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by stakost** [mullwar/telebot#47]
Hi!

I use that method bot.on('callbackQuery', (msg) => {...}) to update inlineButtons, but if set same buttons like last time - I catch nodejs error:
`(node:11721) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
(node:11721) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Could you help to resolve this issue?

**Comment by stakost** [comment]
О! Сразу не заметил что русскоговорящий разработчик :)

Спасибо за АПИ бота!

Есть одна проблема, я создаю inline-кнопки (bot.inlineButton('Мой логин', {callback: 'settings.login'})), нажатие на которые слушают коллбэки. В ответ происходит обновление этих кнопок через метод editText. Если при очередном ответе кнопки не изменились - то node.js шлет ошибку.

**Comment by kosmodrey** [comment]
Привет! Можно посмотреть на пример кода?
