### ISSUE TITLE
bot.start

### ISSUE THREAD

**Issue by Vlad1094** [mullwar/telebot#56]
TypeError: bot.start is not a function

Help me, I am newbie at all...

**Comment by mullwar** [comment]
You probably using stable version of TeleBot (from NPM). Use `bot.connect()`.

**Comment by Vlad1094** [comment]
Thank you!
And another one, how to use bot.mod i paste example source and get error

**Comment by mullwar** [comment]
You should follow stable 1.0.8 version documentation: https://github.com/mullwar/telebot/tree/v1.0.8 or https://www.npmjs.com/package/telebot Those examples should work for you :)

**Comment by Vlad1094** [comment]
Thank you! I just download last repo from git.
Another one...
How can I get file or photo ID
for example i send photo to user, and get this photo ID, to send this another time by id, not by uploading again

**Comment by mullwar** [comment]
You can get it from method response, like this:

```js
bot.on('/start', (msg) => {
    bot.sendPhoto(msg.from.id, './test/data/image.jpg').then((response) => {
        const photo = response.result.photo;
        const photoId = photo[0].file_id;
        console.log('Photo file_id:', photoId);
    });
});
```

**Comment by Vlad1094** [comment]
Thank you!
