### ISSUE TITLE
Send Message without Event

### ISSUE THREAD

**Issue by lucbas** [mullwar/telebot#58]
Hi mullwar

Many thanks for your awesome API!

I'm trying to use your API to send simple notifications without an event and I'm using following code:
`bot.sendMessage(<user-id>, "message");` 

But I get following error:
`(node:5735) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]`

I've created the bot object as following:
`const TeleBot = require('telebot');
const bot = new TeleBot({
    token: '<token>, // Required. Telegram Bot API token.
    webhook: { // Optional. Use webhook instead of polling.
        key: './cert/key.pem', // Optional. Private key for server.
        cert: './cert/cert.pem', // Optional. Public key.
        url: 'https://127.0.0.1', // HTTPS url to send updates to.
        host: '127.0.0.1', // Webhook server host.
        port: 88 // Server port.
    }
});`

I'm listening via an express server.

Could you help me out?

Thank you very much!!

**Comment by mullwar** [comment]
Hi,

Hm, this should work fine. Try this code:
```js
const TeleBot = require('telebot');

const TOKEN = 'TELEGRAM_BOT_TOKEN';
const USER = 000000;

const bot = new TeleBot(TOKEN);

bot.sendMessage(USER, "Hello!");
```

To get idea whats going on, let's print server response to console log:
```js
bot.sendMessage(USER, "Testing!").then((response) => {
    console.log('Ok:', resp);
}).catch((error) => {
    console.log('Error:', error);
});
```

**Comment by lucbas** [comment]
Hi mullwar

Thanks for your fast response, I actually got it working with your code when the full error showed up!

Fix: I had to first start the bot in Telegram itself...

Thank you!

**Comment by mullwar** [comment]
Nice! If you have any questions, don't hesitate to ask. Also, you can join to our Telegram community group: https://goo.gl/gXvm12

**Comment by h22k** [comment]
> Hi,
> 
> Hm, this should work fine. Try this code:
> 
> ```js
> const TeleBot = require('telebot');
> 
> const TOKEN = 'TELEGRAM_BOT_TOKEN';
> const USER = 000000;
> 
> const bot = new TeleBot(TOKEN);
> 
> bot.sendMessage(USER, "Hello!");
> ```
> 
> To get idea whats going on, let's print server response to console log:
> 
> ```js
> bot.sendMessage(USER, "Testing!").then((response) => {
>     console.log('Ok:', response);
> }).catch((error) => {
>     console.log('Error:', error);
> });
> ```

it worked for me. thank you
