### ISSUE TITLE
example KittyBot.js is loading only a default .gif

### ISSUE THREAD

**Issue by hoerbi1000** [mullwar/telebot#60]
If i start the KittyBot.js and say /kittygif you always get the same Gif.
this issue accours since the last commits.

![image](https://cloud.githubusercontent.com/assets/26603435/25717061/9c252e72-3101-11e7-933d-d058b7026eab.png)

**Comment by mullwar** [comment]
Added `serverDownload: true` property which downloads files from your server side. Telegram servers caches files.

**Comment by hoerbi1000** [comment]
thanks for the Fast Support worked for me :)
