### ISSUE TITLE
Can we create a Example Bot for may answering with Emojis

### ISSUE THREAD

**Issue by hoerbi1000** [mullwar/telebot#61]
I would be happy , if there is an explanation how to send an emjoi in BOT-Message.

:)

**Comment by mullwar** [comment]
Just copy-n-paste emojis in message text? :)

```js
bot.sendMessage(chat_id, 'Hello 👋');
```

Some editors may not display them.

**Comment by hoerbi1000** [comment]
okay, which editor you are using mine all have erros on this :(

**Comment by mullwar** [comment]
I recommend you to checkout [Atom](https://atom.io) (free) or [WebStorm](https://www.jetbrains.com/webstorm/) (commercial).
