### ISSUE TITLE
Readme code miss proper requirements

### ISSUE THREAD

**Issue by fparaggio** [mullwar/telebot#62]
Hey guys! I spent lot of time figuring out how to deal with examples code not working!
I just discovered that the examples in this section https://github.com/mullwar/telebot#-quick-examples miss a note regarding the required plugins!
However you did a great job! thanks!

**Comment by mullwar** [comment]
Hello 👋 Hm, examples should work out of the box. I think you talking about `msg.reply` methods which is part of "shortReply" plugin, but it's already included in telebots [default plugin list](https://github.com/mullwar/telebot/blob/master/lib/telebot.js#L7), should work without any additional parameters. How can I reproduce your issue?

**Comment by fparaggio** [comment]
Ok, in my code i had just a plugin loaded. Does default override is expected behaivour ? if yes i would advice to specify that the example requires plugin x . :) thank you

**Comment by mullwar** [comment]
There was a bug with user plugin list (usePlugins) that can overwrite telebot's default list. Can you please sync to latest git version to check if it still breaks the code? Examples should not require any additional plugins.
