### ISSUE TITLE
How to distinguish location event from a reply to an ask for location?

### ISSUE THREAD

**Issue by fparaggio** [mullwar/telebot#63]
I my code I need to ask a location for a specific purpose, so I use the ask plugin with something like : 
```
...
bot.sendMessage(id, 'Please attach your location here!', {ask: 'location'});
...
bot.on('ask.location', msg => { ... } );
...
```
It works perfectly, however I also have another piece of code that trigger on every 'location' event at the same time of the 'ask.location' event :
```
bot.on('location', msg => { ... } );
```
Is there a  way to avoid the last when the location is in reply of a question ('ask.location')? What is your advice?

**Comment by mullwar** [comment]
Explained in [TeleBot Community Group](https://goo.gl/gXvm12).
