### ISSUE TITLE
[ask] telegram message gateway

### ISSUE THREAD

**Issue by frengkys** [mullwar/telebot#64]
is it possible to make telebot become message gateway?
so the id is my phone number but act like bot...
if someone message me(my phone number), my account will auto reply like bot...
is it possible?
pardon me if i ask here... :D

**Comment by mullwar** [comment]
Unfortunately, you can't do this with Telegram Bot API.

**Comment by frengkys** [comment]
so is it possible with telegram api? or is it a way to do it perhaps?

**Comment by mullwar** [comment]
TeleBot uses only [bot API](https://core.telegram.org/bots/api). Telegram API is a client side, there is no Node.js libraries for MTProto protocol at this moment. You can take a look on Telegram CLI project https://github.com/vysheng/tg
