### ISSUE TITLE
Failed to reproduce inlineKeyboard/button example

### ISSUE THREAD

**Issue by t686** [mullwar/telebot#65]
I checked out the examples at:
https://github.com/mullwar/telebot/blob/master/examples/keyboard.js

but unfortunately, **could not get** the bot to render an inline keyboard or button.

_Env:_ Mac OS. Telegram Desktop v 1.1.2

_e.g._
```
bot.on('/inlineKeyboard', msg => {

    let replyMarkup = bot.inlineKeyboard([
        [
            bot.inlineButton('callback', {callback: 'this_is_data'}),
            bot.inlineButton('inline', {inline: 'some query'})
        ], [
            bot.inlineButton('url', {url: 'https://telegram.org'})
        ]
    ]);

    return bot.sendMessage(msg.from.id, 'Inline keyboard example.', {replyMarkup});

});
```
![image](https://cloud.githubusercontent.com/assets/2681631/26255731/e6703db8-3cba-11e7-9f2e-5b3384b368e8.png)

== or == 

```
bot.on('/buttons', msg => {

    let replyMarkup = bot.keyboard([
        [bot.button('contact', 'Your contact'), bot.button('location', 'Your location')],
        ['/back', '/hide']
    ], {resize: true});

    return bot.sendMessage(msg.from.id, 'Button example.', {replyMarkup});

});
```
![image](https://cloud.githubusercontent.com/assets/2681631/26255945/9c6b5c56-3cbb-11e7-91fb-2013eff8903d.png)

**Question:** Shall I activate any _option setting_ in order to allow the bot to reply with buttons/keyboards?
It seems simple and straightforward, but I got stuck.
My other custom commands work just fine.

**P.S:**
The only time I partially succeeded was the code sample from this issue:
https://github.com/mullwar/telebot/issues/29#issuecomment-251720256

```
bot.on('/testkeys', msg => {
  const chatId = msg.chat.id;

  let markup = bot.keyboard([
      ['hello button']
    ], { resize: true, once: true });

    return bot.sendMessage(chatId, 'Hello :)', { markup });

});
```
![image](https://cloud.githubusercontent.com/assets/2681631/26256131/3d9b207a-3cbc-11e7-93df-b97a8c2b6fb2.png)

Thank you in advance 🍻

**Comment by mullwar** [comment]
You are using stable version of TeleBot v1.2.0 from npm which uses old property names. You can clone fresh code from git to get latest features.

**Comment by t686** [comment]
Yeah, that was the problem. 
Downloaded the github version and now it works:

![image](https://cloud.githubusercontent.com/assets/2681631/26257286/487c2f12-3cc0-11e7-8f33-566c4d2fdc40.png)

Cheers
