### ISSUE TITLE
bot.sendMessage().message_id return undefined!

### ISSUE THREAD

**Issue by TheGreatA** [mullwar/telebot#66]
pretty much what the title says!
for Example we have a code like below:
`var q = bot.sendMessage(msg.chat.id, "Hello World").message_id;
console.log(q); //Returns undefined!`

**Comment by mullwar** [comment]
TeleBot is using [Promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise). To get a response from bot action use `.then()` in promise chain:

```js
return bot.sendMessage(msg.chat.id, "Hello World").then((response) => {
    console.log('Response:', response);
}).catch((error) => {
    console.log('Error:', error);
});
```

**Comment by TheGreatA** [comment]
Thank you for your answer, Yes I did manage to do this and Now my problem is solved!
