### ISSUE TITLE
handler is not a function

### ISSUE THREAD

**Issue by fmieres** [mullwar/telebot#68]
I've just started using this library. 
Sometimes my code works and the bot responds, sometimes it does not, and in the console i get a 

    μ-bot :: Error
    TypeError: handler is not a function

I am new to this so i dont know if i am missing something ....

**Comment by mullwar** [comment]
Hello, can you please post your code?

**Comment by fmieres** [comment]
const TeleBot = require('telebot');
    const bot = new TeleBot(process.env.BOT_TOKEN);

    bot.on(['/start', 'audio', 'sticker'], msg => {
      return bot.sendMessage(msg.from.id, 'Bam!');
    });
    bot.start();

**Comment by mullwar** [comment]
This code looks ok. What version of Node.js are you using?

**Comment by Vashiru** [comment]
Shouldn't that be:

```
const TeleBot = require('telebot');
const bot = new TeleBot(process.env.BOT_TOKEN);

bot.on(['/start', 'audio', 'sticker'], (msg) => {
  return bot.sendMessage(msg.from.id, 'Bam!');
});
bot.start();
```
So msg in brackets rather than without?

**Comment by fmieres** [comment]
@mullwar node version is 5.0.0
@Vashiru i can try it but it is indeed possible to use an arrow function with only one parameter without ()

**Comment by mullwar** [comment]
TeleBot library requires Node >= 6.0.

**Comment by fmieres** [comment]
@mullwar Im sorry, node version is v8.0.0 (npm is 5.0.3)

**Comment by fmieres** [comment]
Had nothing to do with your library. Somehow i confused and was using something from another library called micro-bot to start my bot. Just regular node  index.js did the job. 

I'm sorry and thanks for your repsonses. Now it works great!
