### ISSUE TITLE
Chat type parameter

### ISSUE THREAD

**Issue by CarlosLopezES** [mullwar/telebot#73]
Hi,

I want to make a chat discrimination, because some functions i only want to works in private chats, like for example weather alert.

I'm trying with an if and `chat.type = private` and `msg.chat.type = private`, what is the right way to do it?

Thanks!

**Comment by aliforever** [comment]
`message.chat.type === "private"` ?

**Comment by menasheh** [comment]
I don't know if this is the right way...   but I've used `msg.chat.id === msg.from.id`. "From" is the person, if the person matches the chat id, then it's a private chat.  If there is `msg.chat.type` as @aliforever suggests, that would be better. Just `console.log(msg)` and look at the structure.

**Comment by mullwar** [comment]
`message.chat.type` is the correct way to check type of chat (can be either "private", "group", "supergroup" or "channel"). See https://core.telegram.org/bots/api#chat
