### ISSUE TITLE
Does not work this code

### ISSUE THREAD

**Issue by Fomchenkov** [mullwar/telebot#74]
Where problem is?

```
const TeleBot = require('telebot');

const bot = new TeleBot({
    token: '<my-token>',
    webhook: {
        key: './webhook_pkey.pem',
        cert: './webhook_cert.pem',
        url: 'https://<my-ip>',
        host: '0.0.0.0',
        port: 8443
    }
});

bot.on('text', msg => bot.sendMessage(msg.from.id, msg.text));

bot.start();
```

Certificates are signed correctly. Port opened in iptables.
(Polling works successfully)

**Comment by aliforever** [comment]
You haven't set the required fields in webhook like url

**Comment by Fomchenkov** [comment]
In fact there is my ip address. (https://1.234.456.789)

**Comment by Fomchenkov** [comment]
I found error. I had to specify the port next to IP in URL param. It turned out something like `https://1.234.567.890:8443`. Thanks!
