### ISSUE TITLE
How to create one time markup?

### ISSUE THREAD

**Issue by Fomchenkov** [mullwar/telebot#75]
When I create a keyboard, it is shown every time. How can I make it so that after pressing the button, the keyboard disappears?
Now I use this code and the keyboard does not disappear after pressing:
```
let replyMarkup = bot.keyboard([
    ['button1'],
    ['button2']
], {resize: true});
```

**Comment by mullwar** [comment]
Just add a `{ once: true }` parameter: 
```js
bot.keyboard([
    ['button1'],
    ['button2']
], {
    resize: true,
    once: true
});
```

**Comment by Fomchenkov** [comment]
@mullwar Thanks!
