### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by lluiscab** [mullwar/telebot#76]
Would it be possible to use the modifications to only allow the bot to receive messages sent by a specific user / group? I basically would like to cancel all messages except mine and reply to them with some kind of "Action not allowed" message

**Comment by mullwar** [comment]
You can check every incoming message and remove it if not meet your criteria:

```js
const MY_ID = 000000;

bot.mod('message', (data) => {
  const msg = data.message;
  const userId = msg.from.id;

  if (userId !== MY_ID) {
    // Remove this message
    data.message = {};
    // Send deny message
    bot.sendMessage(userId, 'Action not allowed!');
  }

  return data;
});
```

**Comment by lluiscab** [comment]
Working perfectly! You might want to add this as an example ;)
