### ISSUE TITLE
Bot is deployed on Azure but only working when I run it on my local

### ISSUE THREAD

**Issue by RezaRahmati** [mullwar/telebot#77]
Hi

I am new to bots,

I have configured the bot and deployed it to azure, the problem is when I turn off my computer bot stops working, 
If I run npm start on my computer I see logs ob both azure and my local.

What did I miss? I am suspicious about host param 

```
const bot = new TeleBot({
	token: 'mytoken',
	webhook: { 
        url: 'https://myboturl.azurewebsites.net',
        host: '0.0.0.0', 
        port: 443, 
        maxConnections: 40 
    },
```

I set host to ip of my app on azure , and I get this error on both my local and azure console

`Error: listen EADDRNOTAVAIL 40.85.230.182:443`

**Comment by mullwar** [comment]
Try to set `host` parameter to `127.0.0.1` or server ip.

**Comment by RezaRahmati** [comment]
Thanks your solution solved the issue
