### ISSUE TITLE
Support for Text Formatting

### ISSUE THREAD

**Issue by liaujianjie** [mullwar/telebot#86]
Any plans to support [text formatting](https://core.telegram.org/bots/api#text-formatting)?

**Comment by mullwar** [comment]
Hello, I can't find "text formatting" section on a bot api page. What do you mean by this?

**Comment by liaujianjie** [comment]
Sorry, I made a silly mistake.

I tried to pass the formatting option into `parse_mode` (as in the official Telegram docs) instead of `parseMode`.

Thanks for your response!!

**Comment by frengom** [comment]
Hi, I tried the instruction:
`bot.sendMessage(user_id, '<b>bold</b>', {parseMode: 'html'});`
in my node app but I still receive the message as a normal text... Any idea?
