### ISSUE TITLE
How can I set properly webhook parametes?

### ISSUE THREAD

**Issue by Thecave3** [mullwar/telebot#91]
Is it possible to improve the readme or to have a guide to set the webhook properly? 
I'm trying to use this library with Heroku but since the default mode is the polling mechanism after some minutes the app goes idle on Heroku.
It will be very useful if a parameter would be explained better

**Comment by mehranrasulian** [comment]
@Thecave3 [Here's an example](https://github.com/yagop/node-telegram-bot-api/blob/master/examples/webhook/heroku.js) that belongs to another telegram bot lib, hope it works for you.

**Comment by Thecave3** [comment]
exactly what i wanted, thank you!

**Comment by thecryptoguy** [comment]
This is not working now. It says,  bot.setWebHook
