### ISSUE TITLE
How do I handle events?

### ISSUE THREAD

**Issue by sudamar** [mullwar/telebot#93]
**I tried:**

a) ` bot.on('new_chat_member', (event = {}, props, info) => ...`

**and**

b) ` bot.on('new_chat_member', function (msg) { ...`

**Is not working neither. Do I need always use plugin to this?**

**Comment by mullwar** [comment]
Please, see the TeleBot [documented event names](https://github.com/mullwar/telebot#telegram-methods) (just add a camelcase). Use `newChatMembers` event name.
